"""Export generated data as runnable tests for several automation stacks.

These exporters turn the structured API payloads into ready-to-run test files
for Robot Framework, pytest, Playwright, and plain Python. They are pure and
deterministic — built from the payloads regardless of which engine (Claude or
rule-based) produced them — so every emitted file is syntactically valid.

The Python-based exporters (pytest, python) embed the cases as a JSON string and
``json.loads`` them at runtime, so JSON ``true``/``false``/``null`` never leak
into Python source as invalid literals.
"""

from __future__ import annotations

import json
from typing import Any, Dict, List

from app.models.schemas import ApiRequestPayload, ExportArtifacts

# RequestsLibrary keyword per HTTP method (used by the generated .robot suite).
_RF_METHOD_KEYWORD = {
    "GET": "GET On Session",
    "POST": "POST On Session",
    "PUT": "PUT On Session",
    "PATCH": "PATCH On Session",
    "DELETE": "DELETE On Session",
}
_BODY_METHODS = {"POST", "PUT", "PATCH"}


def _safe_name(name: str) -> str:
    """A clean, single-line case name."""
    return (name or "case").replace("\n", " ").strip() or "case"


def _cases(payloads: List[ApiRequestPayload]) -> List[Dict[str, Any]]:
    """A plain, JSON-serialisable list of cases shared by every exporter."""
    return [
        {
            "name": _safe_name(p.name),
            "method": p.method.upper(),
            "path": p.path,
            "headers": p.headers,
            "body": p.body,
            "expected_status": p.expected_status,
            "kind": p.kind.value,
        }
        for p in payloads
    ]


# ---------------------------------------------------------------------------
# Robot Framework (.robot, RequestsLibrary)
# ---------------------------------------------------------------------------
def to_robot_framework(payloads: List[ApiRequestPayload], method: str, path: str) -> str:
    method = method.upper()
    keyword = _RF_METHOD_KEYWORD.get(method, "POST On Session")

    lines: List[str] = [
        "*** Settings ***",
        f"Documentation     Auto-generated API test data for {method} {path}.",
        "...               Generated by the AI Test Data Generator. Point ${BASE_URL}",
        "...               at your environment, then run:  robot generated_api_tests.robot",
        "Library           RequestsLibrary",
        "Library           Collections",
        "Suite Setup       Create Session    api    ${BASE_URL}",
        "",
        "*** Variables ***",
        "${BASE_URL}       http://localhost:8000",
        "",
        "*** Test Cases ***",
    ]
    for p in payloads:
        body_json = json.dumps(p.body)
        lines.append(_safe_name(p.name))
        lines.append(f"    [Documentation]    Expect HTTP {p.expected_status} ({p.kind.value}).")
        lines.append(f"    [Tags]    {p.kind.value}")
        # Build headers with Create Dictionary (not embedded JSON) so Robot resolves
        # %{ENV_VAR} / ${VAR} tokens in values at runtime — the safe way to inject
        # gateway credentials without baking secrets into the file.
        header_args = "    ".join(
            f"{k}={v}" for k, v in p.headers.items()
        )
        if p.headers:
            lines.append(f"    ${{headers}}=    Create Dictionary    {header_args}")
        else:
            lines.append("    ${headers}=    Create Dictionary")
        if method in _BODY_METHODS:
            lines.append(f"    ${{body}}=    Evaluate    json.loads(r'''{body_json}''')    json")
            lines.append(
                f"    ${{resp}}=    {keyword}    api    {path}    json=${{body}}"
                "    headers=${headers}    expected_status=any"
            )
        else:
            lines.append(
                f"    ${{resp}}=    {keyword}    api    {path}"
                "    headers=${headers}    expected_status=any"
            )
        lines.append(
            f"    Should Be Equal As Integers    ${{resp.status_code}}    {p.expected_status}"
        )
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


# ---------------------------------------------------------------------------
# pytest (requests-based, parametrised)
# ---------------------------------------------------------------------------
def to_pytest(payloads: List[ApiRequestPayload], method: str, path: str) -> str:
    cases_json = json.dumps(_cases(payloads), indent=2)
    return (
        '"""Auto-generated API tests by the AI Test Data Generator.\n\n'
        f"Target: {method.upper()} {path}\n"
        "Run:  pip install pytest requests  &&  pytest generated_api_test.py\n"
        'Set BASE_URL to point at your environment.\n"""\n\n'
        "import json\n"
        "import os\n\n"
        "import pytest\n"
        "import requests\n\n"
        'BASE_URL = os.environ.get("BASE_URL", "http://localhost:8000")\n\n'
        f"_CASES = json.loads(r'''{cases_json}''')\n\n"
        '@pytest.mark.parametrize("case", _CASES, ids=[c["name"] for c in _CASES])\n'
        "def test_api(case):\n"
        '    kwargs = {"headers": case["headers"]}\n'
        '    if case["method"] in ("POST", "PUT", "PATCH"):\n'
        '        kwargs["json"] = case["body"]\n'
        '    resp = requests.request(case["method"], BASE_URL + case["path"], **kwargs)\n'
        '    assert resp.status_code == case["expected_status"], (\n'
        '        f"{case[\'name\']}: expected {case[\'expected_status\']}, got {resp.status_code} "\n'
        '        f"({resp.text[:200]})"\n'
        "    )\n"
    )


# ---------------------------------------------------------------------------
# Playwright (@playwright/test, TypeScript)
# ---------------------------------------------------------------------------
def to_playwright(payloads: List[ApiRequestPayload], method: str, path: str) -> str:
    method = method.upper()
    pw_method = method.lower()  # request.post / request.get / ...

    lines: List[str] = [
        "import { test, expect } from '@playwright/test';",
        "",
        "// Auto-generated by the AI Test Data Generator.",
        "const BASE_URL = process.env.BASE_URL ?? 'http://localhost:8000';",
        "",
        f"test.describe('{method} {path}', () => {{",
    ]
    for p in payloads:
        title = _safe_name(p.name).replace("'", "\\'")
        headers = json.dumps(p.headers)
        lines.append(f"  test('{title}', async ({{ request }}) => {{")
        lines.append(f"    const res = await request.{pw_method}(`${{BASE_URL}}{path}`, {{")
        lines.append(f"      headers: {headers},")
        if method in _BODY_METHODS:
            lines.append(f"      data: {json.dumps(p.body)},")
        lines.append("    });")
        lines.append(f"    expect(res.status()).toBe({p.expected_status});")
        lines.append("  });")
        lines.append("")
    lines.append("});")
    return "\n".join(lines).rstrip() + "\n"


# ---------------------------------------------------------------------------
# Plain Python (no test framework — a runnable checker script)
# ---------------------------------------------------------------------------
def to_python(payloads: List[ApiRequestPayload], method: str, path: str) -> str:
    cases_json = json.dumps(_cases(payloads), indent=2)
    return (
        '"""Auto-generated API checks by the AI Test Data Generator.\n\n'
        f"Target: {method.upper()} {path}\n"
        "Run:  pip install requests  &&  python generated_api_checks.py\n"
        "Exits non-zero if any case fails. Set BASE_URL to point at your environment.\n"
        '"""\n\n'
        "import json\n"
        "import os\n"
        "import sys\n\n"
        "import requests\n\n"
        'BASE_URL = os.environ.get("BASE_URL", "http://localhost:8000")\n\n'
        f"CASES = json.loads(r'''{cases_json}''')\n\n"
        "def run() -> int:\n"
        "    failures = 0\n"
        "    for case in CASES:\n"
        '        kwargs = {"headers": case["headers"]}\n'
        '        if case["method"] in ("POST", "PUT", "PATCH"):\n'
        '            kwargs["json"] = case["body"]\n'
        '        resp = requests.request(case["method"], BASE_URL + case["path"], **kwargs)\n'
        '        ok = resp.status_code == case["expected_status"]\n'
        '        status = "PASS" if ok else "FAIL"\n'
        '        print(f"[{status}] {case[\'name\']} -> {resp.status_code} "\n'
        '              f"(expected {case[\'expected_status\']})")\n'
        "        if not ok:\n"
        "            failures += 1\n"
        '    print(f"\\n{len(CASES) - failures}/{len(CASES)} passed")\n'
        "    return 1 if failures else 0\n\n\n"
        'if __name__ == "__main__":\n'
        "    sys.exit(run())\n"
    )


def build_exports(payloads: List[ApiRequestPayload], method: str, path: str) -> ExportArtifacts:
    """Build every export artifact from the generated payloads."""
    return ExportArtifacts(
        robot_framework=to_robot_framework(payloads, method, path),
        pytest=to_pytest(payloads, method, path),
        playwright=to_playwright(payloads, method, path),
        python=to_python(payloads, method, path),
    )
